name: applydash
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/tu-repo
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  domains:
  - domain: applydash.pacoal.dev
    type: PRIMARY
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    scope: BUILD_TIME
  - key: DATABASE_URL
    value: ${DATABASE_URL}
    scope: RUN_TIME
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: ${NEXT_PUBLIC_SUPABASE_URL}
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: ${NEXT_PUBLIC_SUPABASE_URL}
    scope: RUN_TIME
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    scope: RUN_TIME
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    scope: BUILD_TIME
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    scope: RUN_TIME
  - key: NEXT_PUBLIC_SITE_URL
    value: https://applydash.pacoal.dev
    scope: BUILD_TIME
  - key: NEXT_PUBLIC_SITE_URL
    value: https://applydash.pacoal.dev
    scope: RUN_TIME
  build_command: npm run build:do
databases:
- name: applydash-db
  engine: PG
  version: "15"